export type Side = "player" | "ai";
export type CardKind = "follower" | "spell" | "amulet" | "token";

export type CardDef = {
  id: string;
  name: string;
  side: Side | "both";
  kind: CardKind;
  cost: number;
  attack?: number;
  health?: number;
  traits: string[];
  token?: boolean;
  keywords?: ("ward" | "storm" | "rush" | "designated")[];
  evolveId?: string;
  evolveCost?: number;
  image: string;
  text: string;
};

const asset = (filename: string): string => `${import.meta.env?.BASE_URL ?? "/shadowversePt/"}cards/${filename}`;
const card = (definition: CardDef): CardDef => definition;

export const CARDS: Record<string, CardDef> = {
  fairy: card({
    id: "fairy",
    name: "フェアリー",
    side: "both",
    kind: "follower",
    cost: 1,
    attack: 1,
    health: 1,
    traits: ["妖精"],
    token: true,
    image: asset("BP01-T03.jpg"),
    text: "妖精・衍生從者。",
  }),
  fairyWisp: card({
    id: "fairyWisp",
    name: "フェアリーウィスプ",
    side: "player",
    kind: "follower",
    cost: 0,
    attack: 1,
    health: 1,
    traits: ["妖精"],
    token: true,
    image: asset("BP01-T02.jpg"),
    text: "費用0的妖精・衍生從者。",
  }),
  tailwindFairy: card({
    id: "tailwindFairy",
    name: "追い風の妖精",
    side: "player",
    kind: "follower",
    cost: 1,
    attack: 2,
    health: 2,
    traits: ["妖精"],
    image: asset("BP12-010.jpg"),
    text: "自己的回合中，當自己使用卡牌時，若這是本回合第3張卡牌，自己的主戰者回復1點體力；若是第5張卡牌，抽1張牌。每一體『追い風の妖精』都會分別觸發。",
  }),
  naturalAria: card({
    id: "naturalAria",
    name: "自然の妖精姫・アリア",
    side: "player",
    kind: "follower",
    cost: 1,
    attack: 1,
    health: 1,
    traits: ["妖精", "プリンセス"],
    evolveId: "naturalAriaEvo",
    evolveCost: 1,
    image: asset("BP16-001.jpg"),
    text: "【進化・費用1】此卡進化。\n【入場曲】將2張『フェアリー』置入EX區。",
  }),
  naturalAriaEvo: card({
    id: "naturalAriaEvo",
    name: "自然の妖精姫・アリア（EVOLVE）",
    side: "player",
    kind: "follower",
    cost: 0,
    attack: 1,
    health: 1,
    traits: ["妖精", "プリンセス"],
    image: asset("BP16-002.jpg"),
    text: "【進化時】將1體『フェアリー』放置到場上。\n【超進化時】自己場上與EX區所有妖精・衍生從者攻擊力+1／體力+1。",
  }),
  pureWaterFairy: card({
    id: "pureWaterFairy",
    name: "純粋なるウォーターフェアリー",
    side: "player",
    kind: "follower",
    cost: 1,
    attack: 2,
    health: 1,
    traits: ["妖精"],
    image: asset("BP16-015.jpg"),
    text: "【入場曲】【謝幕曲】將1張『フェアリー』置入EX區。",
  }),
  antiAir: card({
    id: "antiAir",
    name: "対空射撃",
    side: "player",
    kind: "spell",
    cost: 1,
    traits: [],
    image: asset("BP18-019.jpg"),
    text: "選擇自己場上1張[エルフ]卡牌，以及對方場上1體從者。將前者返回手牌，對後者造成3點傷害。返回手牌的衍生卡會從遊戲中移除。",
  }),
  vistaElf: card({
    id: "vistaElf",
    name: "眺望のエルフ",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 3,
    traits: ["エルフ族"],
    image: asset("BP20-016.jpg"),
    text: "【入場曲】將1張『フェアリーウィスプ』置入EX區。",
  }),
  fairyDragon: card({
    id: "fairyDragon",
    name: "フェアリードラゴン",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 0,
    health: 4,
    traits: ["妖精", "精霊"],
    keywords: ["ward"],
    image: asset("BP06-007.jpg"),
    text: "【守護】\n【入場曲】此卡攻擊力+X。X為自己場上與EX區妖精・衍生卡張數合計。\n【謝幕曲】將『フェアリーウィスプ』與『フェアリー』各1張置入EX區。",
  }),
  fairyBladeAmatsu: card({
    id: "fairyBladeAmatsu",
    name: "フェアリーブレイダー・アマツ",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 2,
    traits: ["エルフ族", "精霊"],
    image: asset("BP06-003.jpg"),
    text: "【入場曲】將1張『フェアリー』置入EX區。自己EX區所有妖精・從者攻擊力+1／體力+1。\n【起動】將此卡橫置：選擇自己場上最多2體原本費用1以下的妖精・從者。它們獲得【疾走】。",
  }),
  forestFairy: card({
    id: "forestFairy",
    name: "フォレストフェアリー",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 2,
    traits: ["妖精"],
    evolveId: "forestFairyEvo",
    evolveCost: 1,
    image: asset("BP13-013.jpg"),
    text: "【進化・費用1】此卡進化。",
  }),
  forestFairyEvo: card({
    id: "forestFairyEvo",
    name: "フォレストフェアリー（EVOLVE）",
    side: "player",
    kind: "follower",
    cost: 0,
    attack: 3,
    health: 3,
    traits: ["妖精"],
    image: asset("BP13-014.jpg"),
    text: "【進化時】將『フェアリーウィスプ』與『フェアリー』各1張置入EX區。若自己EX區的妖精・從者為3張以上，自己的主戰者回復2點體力。",
  }),
  breathFairyDancer: card({
    id: "breathFairyDancer",
    name: "ブレスフェアリーダンサー",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 3,
    traits: ["妖精"],
    image: asset("BP01-011.jpg"),
    text: "【入場曲】自己場上其他妖精・從者，以及自己EX區所有妖精・從者攻擊力+1／體力+1。",
  }),
  fairyArcher: card({
    id: "fairyArcher",
    name: "妖精の弓使い",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 1,
    traits: ["妖精"],
    image: asset("BP13-018.jpg"),
    text: "【入場曲】將1體『フェアリー』放置到場上。查看自己牌庫最上面3張牌，可以公開其中1張妖精・卡牌並加入手牌；其餘以任意順序置於牌庫底部。",
  }),
  reverseAmatsu: card({
    id: "reverseAmatsu",
    name: "リバースブレイダー・アマツ",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 2,
    traits: ["エルフ族", "精霊"],
    keywords: ["ward"],
    evolveId: "reverseAmatsuEvo",
    evolveCost: 1,
    image: asset("BP15-002.jpg"),
    text: "【守護】\n【進化・費用1】此卡進化。",
  }),
  reverseAmatsuEvo: card({
    id: "reverseAmatsuEvo",
    name: "リバースブレイダー・アマツ（EVOLVE）",
    side: "player",
    kind: "follower",
    cost: 0,
    attack: 3,
    health: 3,
    traits: ["エルフ族", "精霊"],
    keywords: ["ward"],
    image: asset("BP15-003.jpg"),
    text: "【守護】\n【進化時】選擇對方場上1體從者。若自己EX區有3張以上卡牌，將其破壞；若自己EX區有3張以上妖精・卡牌，再對其主戰者造成2點傷害。",
  }),
  fairyland: card({
    id: "fairyland",
    name: "ティターニアの妖精郷",
    side: "player",
    kind: "amulet",
    cost: 2,
    traits: ["妖精", "プリンセス"],
    image: asset("SD01-002.jpg"),
    text: "只要此卡在場上，自己場上所有妖精・衍生卡都獲得【指定攻擊】。自己場上出現妖精・衍生卡時，使其攻擊力+1／體力+1。\n【入場曲】自己場上所有妖精・衍生卡攻擊力+1／體力+1。",
  }),
  riotousGarden: card({
    id: "riotousGarden",
    name: "繚乱の庭",
    side: "player",
    kind: "amulet",
    cost: 2,
    traits: ["妖精"],
    image: asset("BP21-018.jpg"),
    text: "【入場曲】將1體『フェアリー』放置到場上。\n【起動】將此卡橫置並置入墓場：對對方1體從者造成X點傷害。X為自己場上與EX區妖精・衍生從者的張數合計。",
  }),
  wonderTree: card({
    id: "wonderTree",
    name: "ワンダーツリー",
    side: "player",
    kind: "amulet",
    cost: 2,
    traits: ["妖精"],
    image: asset("BP13-012.jpg"),
    text: "【入場曲】將1張『フェアリー』置入EX區。\n【起動】將此卡橫置並置入墓場：抽2張牌。此能力只能在自己EX區有3張以上妖精・從者時使用。",
  }),
  miasmaAria: card({
    id: "miasmaAria",
    name: "瘴気の妖精姫・アリア",
    side: "player",
    kind: "follower",
    cost: 3,
    attack: 3,
    health: 3,
    traits: ["妖精", "プリンセス"],
    evolveId: "miasmaAriaEvo",
    evolveCost: 1,
    image: asset("BP13-003.jpg"),
    text: "此卡不能從EX區使用。只要此卡在場上或EX區，自己場上所有妖精・衍生從者獲得【突進】。\n【入場曲】將1張『フェアリー』置入EX區。\n【謝幕曲】可以將此卡置入EX區。",
  }),
  miasmaAriaEvo: card({
    id: "miasmaAriaEvo",
    name: "瘴気の妖精姫・アリア（EVOLVE）",
    side: "player",
    kind: "follower",
    cost: 0,
    attack: 4,
    health: 4,
    traits: ["妖精", "プリンセス"],
    image: asset("BP13-004.jpg"),
    text: "只要此卡在場上，自己場上所有妖精・衍生從者獲得【突進】。\n【進化時】從自己牌庫中找出1張原本費用2以下的妖精・護符，放置到場上。\n【謝幕曲】可以將此卡置入EX區。",
  }),
  bouquetFairy: card({
    id: "bouquetFairy",
    name: "花束の妖精",
    side: "player",
    kind: "follower",
    cost: 3,
    attack: 2,
    health: 2,
    traits: ["妖精"],
    image: asset("BP15-017.jpg"),
    text: "【入場曲】將1張『フェアリーウィスプ』置入EX區。\n【起動】將此卡橫置，並消滅EX區1張卡：選擇對方場上1體從者返回手牌。返回手牌的衍生卡會從遊戲中移除。",
  }),
  wingQueen: card({
    id: "wingQueen",
    name: "翅の女王・ティターニア",
    side: "player",
    kind: "follower",
    cost: 3,
    attack: 1,
    health: 1,
    traits: ["妖精", "プリンセス"],
    image: asset("BP21-004.jpg"),
    text: "【入場曲】若自己EX區有2張以上妖精・卡牌，從自己牌庫中找出1張「不與此卡同名、原本費用3以下的妖精・從者」，放置到場上。\n【起動・費用1】將此卡橫置並置入墓場：破壞對方1體從者，其主人將1體『フェアリー』放置到場上。此能力只能在自己EX區正好有5張妖精・卡牌時使用。",
  }),
  queenCynthia: card({
    id: "queenCynthia",
    name: "クイーンセイバー・シンシア",
    side: "player",
    kind: "follower",
    cost: 6,
    attack: 4,
    health: 6,
    traits: ["エルフ族"],
    image: asset("BP07-003.jpg"),
    text: "只要此卡在場上，自己場上所有妖精・衍生卡都獲得【疾走】【指定攻擊】。自己場上出現妖精・衍生卡時，使其攻擊力+2。\n【入場曲】將1張『フェアリーウィスプ』置入EX區。自己場上所有妖精・衍生卡攻擊力+2。",
  }),

  levinMiim: card({
    id: "levinMiim",
    name: "レヴィオンの魔術師・ミイム",
    side: "player",
    kind: "follower",
    cost: 1,
    attack: 2,
    health: 2,
    traits: ["レヴィオン", "ロイヤル"],
    keywords: ["ward"],
    image: asset("BP13-032.jpg"),
    text: "【守護】\n自己的結束階段來臨時，若自己墓場的雷維翁・卡牌為5張以上，自己的主戰者體力+1。\n【入場曲】可以捨棄手牌中1張雷維翁・卡牌：抽1張牌。",
  }),
  levinRunes: card({
    id: "levinRunes",
    name: "レヴィオンの見習い・ルネス",
    side: "player",
    kind: "follower",
    cost: 1,
    attack: 1,
    health: 1,
    traits: ["レヴィオン", "ロイヤル"],
    evolveId: "levinRunesEvo",
    evolveCost: 3,
    image: asset("BP13-026.jpg"),
    text: "【進化・費用3】此卡進化。\n【入場曲】可以捨棄手牌中1張雷維翁・卡牌：從自己牌庫中找出1張「卡名包含『アルベール』的[ロイヤル]從者」加入手牌。",
  }),
  levinRunesEvo: card({
    id: "levinRunesEvo",
    name: "レヴィオンの見習い・ルネス（EVOLVE）",
    side: "player",
    kind: "follower",
    cost: 0,
    attack: 2,
    health: 2,
    traits: ["レヴィオン", "ロイヤル"],
    image: asset("BP13-027.jpg"),
    text: "自己的回合中，當「卡名包含『アルベール』的[ロイヤル]從者」出現在自己場上時，可以支付【費用1】：選擇對方場上1體從者，對其造成3點傷害。\n【進化時】可以將手牌中1張「原本費用X以下、卡名包含『アルベール』的[ロイヤル]從者」放置到場上。X為自己的PP最大值。",
  }),
  tentacleBite: card({
    id: "tentacleBite",
    name: "テンタクルバイト",
    side: "player",
    kind: "spell",
    cost: 1,
    traits: ["ロイヤル"],
    image: asset("BP16-026.jpg"),
    text: "使用此卡時，必須橫置自己場上1體雷維翁・從者作為追加費用。\n選擇對方場上1體從者，對其造成4點傷害。自己的主戰者體力+2。若自己場上有「卡名包含『ユリウス』的從者」，抽1張牌。",
  }),
  levinSisters: card({
    id: "levinSisters",
    name: "レヴィオンシスターズ登場！",
    side: "player",
    kind: "spell",
    cost: 1,
    traits: ["レヴィオン", "ロイヤル"],
    image: asset("BP13-035.jpg"),
    text: "使用此卡時，可以將費用+4。\n從自己牌庫中找出『レヴィオンの副団長・マイム』『レヴィオンの魔術師・ミイム』『レヴィオンの武闘家・メイム』其中1張加入手牌。若費用+4，改為各找出1張直接放置到場上。",
  }),
  gawain: card({
    id: "gawain",
    name: "約束の栄光・ガウェイン",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 3,
    health: 3,
    traits: ["ロイヤル"],
    keywords: ["rush"],
    image: asset("BP18-023.jpg"),
    text: "【突進】\n【入場曲】若自己墓場的[ロイヤル]從者為5張以上，抽1張牌。10張以上，此卡獲得【疾走】，自己的主戰者體力+2。15張以上，此卡獲得【威圧】【オーラ】。20張以上，此卡攻擊力+7／體力+7。",
  }),
  levinAxeGeno: card({
    id: "levinAxeGeno",
    name: "レヴィオンアックス・ジェノ",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 3,
    health: 2,
    traits: ["レヴィオン", "ロイヤル"],
    image: asset("SD07-012.jpg"),
    text: "此卡從自己手牌被捨棄時，查看自己牌庫最上面1張牌，若是雷維翁・卡牌可以公開並加入手牌。\n只要自己墓場的雷維翁・卡牌為5張以上，此卡獲得【疾走】。",
  }),
  levinDuke: card({
    id: "levinDuke",
    name: "レヴィオンデューク・ユリウス",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 0,
    health: 4,
    traits: ["レヴィオン", "ロイヤル"],
    image: asset("BP02-027.jpg"),
    text: "【快速】【起動】將此卡橫置：選擇對方場上1體從者，對其造成1點傷害。\n（模擬器簡化：僅能在自己的主階段起動。）",
  }),
  levinMaim: card({
    id: "levinMaim",
    name: "レヴィオンの副団長・マイム",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 2,
    traits: ["レヴィオン", "ロイヤル"],
    evolveId: "levinMaimEvo",
    evolveCost: 1,
    image: asset("BP13-030.jpg"),
    text: "【進化・費用1】此卡進化。\n【入場曲】選擇對方場上1體從者。若自己墓場的雷維翁・卡牌為5張以上，對其造成3點傷害。",
  }),
  levinMaimEvo: card({
    id: "levinMaimEvo",
    name: "レヴィオンの副団長・マイム（EVOLVE）",
    side: "player",
    kind: "follower",
    cost: 0,
    attack: 3,
    health: 3,
    traits: ["レヴィオン", "ロイヤル"],
    image: asset("BP13-031.jpg"),
    text: "【進化時】查看自己牌庫最上面4張牌，可以公開其中1張雷維翁・卡牌並加入手牌；其餘以任意順序置於牌庫底部。",
  }),
  levinMeim: card({
    id: "levinMeim",
    name: "レヴィオンの武闘家・メイム",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 3,
    health: 2,
    traits: ["レヴィオン", "ロイヤル"],
    keywords: ["rush"],
    image: asset("BP13-033.jpg"),
    text: "【突進】\n只要自己墓場的雷維翁・卡牌為5張以上，此卡獲得【指定攻擊】與「【攻擊時】此卡攻擊力+2／體力+1」。",
  }),
  levinArcher: card({
    id: "levinArcher",
    name: "レヴィオンの弓使い",
    side: "player",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 2,
    traits: ["レヴィオン", "ロイヤル"],
    image: asset("BP21-034.jpg"),
    text: "【入場曲】查看自己牌庫最上面2張牌，可以公開其中1張雷維翁・卡牌並加入手牌；其餘置入墓場。\n【起動】將此卡橫置：選擇對方場上1體從者。若自己墓場的雷維翁・卡牌為5張以上，對其造成3點傷害。",
  }),
  levinTranscend: card({
    id: "levinTranscend",
    name: "レヴィオンの超越者・ユリウス",
    side: "player",
    kind: "follower",
    cost: 3,
    attack: 3,
    health: 4,
    traits: ["レヴィオン", "ロイヤル"],
    image: asset("BP21-022.jpg"),
    text: "【入場曲】公開手牌中2張雷維翁・卡牌：從下列選擇1項。若自己墓場的雷維翁・卡牌為5張以上，改為最多選擇3項。\n①破壞對方場上1體從者。②對對方主戰者造成3點傷害。③抽2張牌，捨棄自己1張手牌。",
  }),
  levinJustice: card({
    id: "levinJustice",
    name: "レヴィオンの正義",
    side: "player",
    kind: "spell",
    cost: 3,
    traits: ["レヴィオン", "ロイヤル"],
    image: asset("BP13-025.jpg"),
    text: "使用此卡時，可以將費用+2。\n選擇對方場上1體從者，對其造成3點傷害。從自己牌庫中找出1張『レヴィオンデューク・ユリウス』放置到場上。若費用+2，再從自己牌庫中找出1張『レヴィオンセイバー・アルベール』放置到場上。",
  }),
  brutalGeno: card({
    id: "brutalGeno",
    name: "暴威の武人・ジェノ",
    side: "player",
    kind: "follower",
    cost: 4,
    attack: 4,
    health: 3,
    traits: ["ロイヤル"],
    image: asset("BP13-028.jpg"),
    text: "使用此卡時，可以將自己場上1體原本費用3以下的雷維翁・從者置入墓場：費用-3。\n【入場曲】選擇對方場上1體從者，對其造成4點傷害。",
  }),
  levinAlbert: card({
    id: "levinAlbert",
    name: "レヴィオンの迅雷・アルベール",
    side: "player",
    kind: "follower",
    cost: 4,
    attack: 4,
    health: 5,
    traits: ["レヴィオン", "ロイヤル"],
    keywords: ["storm"],
    image: asset("BP16-021.jpg"),
    text: "【疾走】\n【入場曲】選擇自己場上其他1體雷維翁・從者，使其攻擊力+1。\n【起動・費用3】使此卡直立。此能力只能在自己墓場的[ロイヤル]從者為10張以上時使用，每回合1次。",
  }),

  destructionJoy: card({
    id: "destructionJoy",
    name: "破壊の愉悦",
    side: "ai",
    kind: "spell",
    cost: 0,
    traits: ["絶傑", "アイドル"],
    image: asset("BP08-051.jpg"),
    text: "若自己場上有偶像・卡牌，回復1點PP。若自己場上有『破壊の絶傑・リーシェナ』，再抽1張牌。",
  }),
  destructionHermit: card({
    id: "destructionHermit",
    name: "破壊の隠者",
    side: "ai",
    kind: "follower",
    cost: 1,
    attack: 2,
    health: 2,
    traits: ["絶傑", "アイドル"],
    image: asset("BP15-054.jpg"),
    text: "【入場曲】選擇對方場上1體從者。若自己場上有3張以上偶像・卡牌，對其造成3點傷害。",
  }),
  annihilationSong: card({
    id: "annihilationSong",
    name: "殲滅の歌声",
    side: "ai",
    kind: "spell",
    cost: 1,
    traits: ["絶傑", "アイドル"],
    image: asset("BP20-045.jpg"),
    text: "選擇1項：①破壞自己場上1張偶像・卡牌，抽1張牌；②將1張『新約・白の章』（白蛋）放置到場上。",
  }),
  destructionWilderness: card({
    id: "destructionWilderness",
    name: "破壊の荒野",
    side: "ai",
    kind: "amulet",
    cost: 1,
    traits: ["絶傑", "アイドル"],
    image: asset("BP20-055.jpg"),
    text: "【入場曲】查看自己牌庫最上面2張牌，可以公開其中1張絕傑・偶像・卡牌並加入手牌；其餘以任意順序置於牌庫底部。\n【起動】將此卡置入墓場：將自己場上其他1張偶像・卡牌置入墓場。",
  }),
  whiteBlackChapter: card({
    id: "whiteBlackChapter",
    name: "白の章・黒の章",
    side: "ai",
    kind: "spell",
    cost: 2,
    traits: ["絶傑", "アイドル"],
    image: asset("BP05-045.jpg"),
    text: "【快速】選擇對方場上1體從者，對其造成2點傷害。若自己場上有2張以上偶像・卡牌，再對其主戰者造成2點傷害，自己的主戰者回復2點體力。",
  }),
  destructionServant: card({
    id: "destructionServant",
    name: "破壊の従者",
    side: "ai",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 2,
    traits: ["絶傑", "アイドル"],
    evolveId: "destructionServantEvo",
    evolveCost: 2,
    image: asset("BP05-048.jpg"),
    text: "【進化・費用2】此卡進化。\n【入場曲】若自己場上有3張以上偶像・卡牌，本回合中此卡的進化費用變為0。",
  }),
  destructionServantEvo: card({
    id: "destructionServantEvo",
    name: "破壊の従者（EVOLVE）",
    side: "ai",
    kind: "follower",
    cost: 0,
    attack: 4,
    health: 4,
    traits: ["絶傑", "アイドル"],
    image: asset("BP05-049.jpg"),
    text: "【進化時】選擇對方場上1體從者，對其與其主戰者各造成2點傷害。",
  }),
  returningDissonance: card({
    id: "returningDissonance",
    name: "舞い戻る奏絶",
    side: "ai",
    kind: "spell",
    cost: 2,
    traits: ["絶傑", "アイドル"],
    image: asset("BP15-045.jpg"),
    text: "使用此卡時，必須消滅自己墓場中1張名稱包含『リーシェナ』的從者作為追加費用。若自己場上有2張以上偶像・卡牌，從牌庫中找出1張名稱包含『リーシェナ』的從者，放置到場上。",
  }),
  dissonanceWorshipper: card({
    id: "dissonanceWorshipper",
    name: "奏絶の崇拝者",
    side: "ai",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 3,
    traits: ["絶傑", "アイドル"],
    image: asset("BP15-049.jpg"),
    text: "【入場曲】查看自己牌庫最上面3張牌，可以公開其中1張偶像・卡牌並加入手牌；其餘以任意順序置於牌庫底部。",
  }),
  manifestedLishenna: card({
    id: "manifestedLishenna",
    name: "奏絶の顕現・リーシェナ",
    side: "ai",
    kind: "follower",
    cost: 2,
    attack: 1,
    health: 1,
    traits: ["絶傑", "アイドル"],
    image: asset("BP20-037.jpg"),
    text: "【入場曲】選擇1項：①破壞自己場上其他1張偶像・卡牌，將1張『奏絶の独唱』置入EX區；②將1張『新約・白の章』（白蛋）放置到場上。",
  }),
  axia: card({
    id: "axia",
    name: "破壊の継承者・アクシア",
    side: "ai",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 2,
    traits: ["絶傑", "アイドル"],
    evolveId: "axiaEvo",
    evolveCost: 1,
    image: asset("BP20-040.jpg"),
    text: "【進化・費用1】此卡進化。",
  }),
  axiaEvo: card({
    id: "axiaEvo",
    name: "破壊の継承者・アクシア（EVOLVE）",
    side: "ai",
    kind: "follower",
    cost: 0,
    attack: 3,
    health: 3,
    traits: ["絶傑", "アイドル"],
    image: asset("BP20-041.jpg"),
    text: "每回合1次，當自己場上有偶像・護符登場時，選擇對方場上1體從者，對其造成2點傷害。\n【進化時】將自己場上其他1張偶像・卡牌置入墓場：從牌庫找出1張名稱包含『リーシェナ』的從者並加入手牌。\n【超進化時】對對方主戰者造成與自己場上偶像・卡牌張數相同的傷害。",
  }),
  destructionPrayer: card({
    id: "destructionPrayer",
    name: "破壊の祈祷者",
    side: "ai",
    kind: "follower",
    cost: 2,
    attack: 2,
    health: 3,
    traits: ["絶傑", "アイドル"],
    image: asset("BP20-048.jpg"),
    text: "【起動】將此卡橫置，並將自己場上其他1張偶像・卡牌置入墓場：選擇對方主戰者或對方場上1體從者，對其造成2點傷害。",
  }),
  destructionAffirmerEvo: card({
    id: "destructionAffirmerEvo",
    name: "破壊の肯定者（EVOLVE）",
    side: "ai",
    kind: "follower",
    cost: 0,
    attack: 2,
    health: 2,
    traits: ["絶傑", "アイドル"],
    keywords: ["designated"],
    image: asset("BP20-051.jpg"),
    text: "【指定攻擊】\n【進化時】將自己場上其他1張偶像・卡牌置入墓場：抽1張牌。此構築沒有進化前本體，本卡僅作為進化區資訊保留。",
  }),
  destructionFanatic: card({
    id: "destructionFanatic",
    name: "破壊の狂信者",
    side: "ai",
    kind: "follower",
    cost: 3,
    attack: 3,
    health: 4,
    traits: ["絶傑", "アイドル"],
    image: asset("BP08-050.jpg"),
    text: "【入場曲】若自己場上有3張以上偶像・卡牌，選擇對方場上1體從者並將其破壞；對其主戰者造成2點傷害，自己的主戰者回復2點體力。",
  }),
  destructiveLishenna: card({
    id: "destructiveLishenna",
    name: "奏絶の破壊・リーシェナ",
    side: "ai",
    kind: "follower",
    cost: 3,
    attack: 3,
    health: 3,
    traits: ["絶傑", "アイドル"],
    evolveId: "destructiveLishennaEvo",
    evolveCost: 1,
    image: asset("BP15-039.jpg"),
    text: "【進化・費用1】此卡進化。\n【入場曲】若自己場上有3張以上偶像・卡牌，將1張『奏絶の独唱』置入EX區。",
  }),
  destructiveLishennaEvo: card({
    id: "destructiveLishennaEvo",
    name: "奏絶の破壊・リーシェナ（EVOLVE）",
    side: "ai",
    kind: "follower",
    cost: 0,
    attack: 4,
    health: 4,
    traits: ["絶傑", "アイドル"],
    image: asset("BP15-040.jpg"),
    text: "【進化時】查看自己牌庫最上面4張牌，可以將其中最多2張偶像・卡牌置入EX區；其餘以任意順序置於牌庫底部。",
  }),
  originalLishenna: card({
    id: "originalLishenna",
    name: "破壊の絶傑・リーシェナ",
    side: "ai",
    kind: "follower",
    cost: 4,
    attack: 2,
    health: 4,
    traits: ["絶傑", "アイドル"],
    image: asset("BP05-037.jpg"),
    text: "【入場曲】將『白き破壊のアーティファクト』與『黒き破壊のアーティファクト』各1張置入EX區。",
  }),
  zelgenea: card({
    id: "zelgenea",
    name: "《世界》・ゼルガネイア",
    side: "ai",
    kind: "follower",
    cost: 5,
    attack: 5,
    health: 5,
    traits: ["世界"],
    image: asset("BP10-109.jpg"),
    text: "【入場曲】選擇對方場上1體從者。若自己場上沒有其他從者，將其破壞並抽1張牌。\n【入場曲】若自己主戰者體力為10以下，回復5點體力。\n【起動・費用10】消滅墓場中的此卡：可以將進化區的『大いなる《世界》・ゼルガネイア』置入EX區。",
  }),
  greatZelgenea: card({
    id: "greatZelgenea",
    name: "大いなる《世界》・ゼルガネイア",
    side: "ai",
    kind: "follower",
    cost: 0,
    attack: 10,
    health: 10,
    traits: ["世界"],
    token: true,
    image: asset("BP10-110.jpg"),
    text: "自己的結束階段來臨時，若此卡位於EX區，對對方主戰者及對方場上所有從者造成4點傷害。\n【入場曲】對對方主戰者及對方場上所有從者造成10點傷害。",
  }),
  solo: card({
    id: "solo",
    name: "奏絶の独唱",
    side: "ai",
    kind: "spell",
    cost: 0,
    traits: ["絶傑", "アイドル"],
    token: true,
    image: asset("BP20-T13.jpg"),
    text: "使用此卡時，可以橫置自己場上任意張數的偶像・卡牌作為追加費用。選擇對方場上1體從者，對其造成「作為追加費用而橫置的卡牌張數×2」點傷害。",
  }),
  newWhite: card({
    id: "newWhite",
    name: "新約・白の章",
    side: "ai",
    kind: "amulet",
    cost: 1,
    traits: ["絶傑", "アイドル"],
    token: true,
    image: asset("BP20-T03.jpg"),
    text: "俗稱白蛋。\n【謝幕曲】將1張『新約・黒の章』（黑蛋）放置到場上，自己的主戰者回復1點體力。\n【起動】橫置自己場上3張偶像・卡牌：將此卡置入墓場。",
  }),
  newBlack: card({
    id: "newBlack",
    name: "新約・黒の章",
    side: "ai",
    kind: "amulet",
    cost: 1,
    traits: ["絶傑", "アイドル"],
    token: true,
    image: asset("BP20-T04.jpg"),
    text: "俗稱黑蛋。\n【謝幕曲】將1張『新約・白の章』（白蛋）放置到場上，對方主戰者受到1點傷害。\n【起動】橫置自己場上3張偶像・卡牌：將此卡置入墓場。",
  }),
  whiteArtifact: card({
    id: "whiteArtifact",
    name: "白き破壊のアーティファクト",
    side: "ai",
    kind: "amulet",
    cost: 1,
    traits: ["絶傑", "アイドル"],
    token: true,
    image: asset("BP05-T01.jpg"),
    text: "自己的主要階段來臨時，自己的主戰者回復2點體力。",
  }),
  blackArtifact: card({
    id: "blackArtifact",
    name: "黒き破壊のアーティファクト",
    side: "ai",
    kind: "amulet",
    cost: 2,
    traits: ["絶傑", "アイドル"],
    token: true,
    image: asset("BP05-T02.jpg"),
    text: "自己的主要階段來臨時，對方主戰者受到2點傷害。",
  }),
};

export const PLAYER_DECK: [string, number][] = [
  ["tailwindFairy", 2], ["naturalAria", 3], ["pureWaterFairy", 3],
  ["antiAir", 2], ["vistaElf", 3], ["fairyDragon", 1],
  ["fairyBladeAmatsu", 3], ["forestFairy", 2], ["breathFairyDancer", 3],
  ["fairyArcher", 3], ["reverseAmatsu", 3], ["fairyland", 1],
  ["riotousGarden", 1], ["wonderTree", 1], ["miasmaAria", 3],
  ["bouquetFairy", 1], ["wingQueen", 3], ["queenCynthia", 2],
];

export const PLAYER_EVOLVE: [string, number][] = [
  ["naturalAriaEvo", 2], ["forestFairyEvo", 2],
  ["reverseAmatsuEvo", 3], ["miasmaAriaEvo", 3],
];

export const LEVIN_DECK: [string, number][] = [
  ["levinMiim", 3], ["levinRunes", 3], ["tentacleBite", 3],
  ["levinSisters", 3], ["gawain", 3], ["levinAxeGeno", 3],
  ["levinDuke", 2], ["levinMaim", 3], ["levinMeim", 3],
  ["levinArcher", 3], ["levinTranscend", 3], ["levinJustice", 2],
  ["brutalGeno", 3], ["levinAlbert", 3],
];

// 實戰上進化區只會用到這6張（牌表上的小日向美穂×3、五十嵐響子×1為湊數，不收錄）。
export const LEVIN_EVOLVE: [string, number][] = [
  ["levinRunesEvo", 3], ["levinMaimEvo", 3],
];

export const AI_DECK: [string, number][] = [
  ["destructionJoy", 3], ["destructionHermit", 3], ["annihilationSong", 3],
  ["destructionWilderness", 3], ["whiteBlackChapter", 3],
  ["destructionServant", 2], ["returningDissonance", 3],
  ["dissonanceWorshipper", 3], ["manifestedLishenna", 3], ["axia", 3],
  ["destructionPrayer", 2], ["destructionFanatic", 3],
  ["destructiveLishenna", 3], ["originalLishenna", 2], ["zelgenea", 1],
];

export const AI_EVOLVE: [string, number][] = [
  ["destructionServantEvo", 2], ["axiaEvo", 3],
  ["destructiveLishennaEvo", 3], ["destructionAffirmerEvo", 1],
  ["greatZelgenea", 1],
];

export const cardName = (id: string) => CARDS[id]?.name ?? id;
export const isFairyCard = (id: string) => CARDS[id]?.traits.includes("妖精") ?? false;
export const isIdolCard = (id: string) => CARDS[id]?.traits.includes("アイドル") ?? false;
export const isLishenna = (id: string) => CARDS[id]?.name.includes("リーシェナ") ?? false;
export const isLevinCard = (id: string) => CARDS[id]?.traits.includes("レヴィオン") ?? false;
export const isRoyalCard = (id: string) => CARDS[id]?.traits.includes("ロイヤル") ?? false;
export const isAlbert = (id: string) => (CARDS[id]?.name.includes("アルベール") && isRoyalCard(id)) ?? false;

export type PlayerDeckId = "fairy" | "levin";
export const PLAYER_DECKS: Record<PlayerDeckId, { label: string; main: [string, number][]; evolve: [string, number][] }> = {
  fairy: { label: "妖精エルフ", main: PLAYER_DECK, evolve: PLAYER_EVOLVE },
  levin: { label: "レヴィオンロイヤル", main: LEVIN_DECK, evolve: LEVIN_EVOLVE },
};
